name: class data

on:
  push:
    branches: [ main ]
    
  pull_request:
    branches: [ main ]

jobs:

  class-data:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
      
    - name: Restore tests dependencies (class data)
      run: dotnet restore ./src/Testing.Bank.Tests.ClassData
      
    - name: Build tests (class data)
      run: dotnet build ./src/Testing.Bank.Tests.ClassData --no-restore
      
    - name: Run tests (class data)
      run: dotnet test ./src/Testing.Bank.Tests.ClassData --no-build --verbosity normal         
            
