name: inline data

on:
  push:
    branches: [ main ]
    
  pull_request:
    branches: [ main ]

jobs:

  inline-data:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
      
    - name: Restore tests dependencies (inline data)
      run: dotnet restore ./src/Testing.Bank.Tests.InlineData
      
    - name: Build tests (inline data)
      run: dotnet build ./src/Testing.Bank.Tests.InlineData --no-restore
      
    - name: Run tests (inline data)
      run: dotnet test ./src/Testing.Bank.Tests.InlineData --no-build --verbosity normal         
     
