name: member data

on:
  push:
    branches: [ main ]
    
  pull_request:
    branches: [ main ]

jobs:

  member-data:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        

    - name: Restore tests dependencies (member data)
      run: dotnet restore ./src/Testing.Bank.Tests.MemberData
      
    - name: Build tests (member data)
      run: dotnet build ./src/Testing.Bank.Tests.MemberData --no-restore
      
    - name: Run tests (member data)
      run: dotnet test ./src/Testing.Bank.Tests.MemberData --no-build --verbosity normal   
      